"use strict";

const propertiesIterator = (values = '', property = '', suffix = '') => (
  values.map((position) => `${property}-${position}${suffix ? `-${suffix}` : ''}`).flat()
);

const logicalProperties = (property, suffix) => propertiesIterator(['block', 'block-start', 'block-end', 'inline', 'inline-start', 'inline-end'], property, suffix);
const tblrProperties = (property, suffix) => propertiesIterator(['top', 'bottom', 'left', 'right'], property, suffix);

module.exports = {
  "plugins": [
    "stylelint-order",
  ],
  "rules": {
    "order/properties-alphabetical-order": null,
    "order/order": [
      [
        "custom-properties",
        "dollar-variables",
        {
          "type": "at-rule",
          "name": "extend",
          "hasBlock": false,
        },
        "declarations",
        "rules",
        {
          "type": "at-rule",
          "name": "return",
        },
      ],
    ],
    "order/properties-order": [
      [
        {
          "emptyLineBefore": "never",
          "properties": [
            "content",
          ],
        },
        {
          "emptyLineBefore": "never",
          "order": "flexible",
          "properties": [
            "container",
            "container-name",
            "container-type",
          ],
        },
        {
          "emptyLineBefore": "never",
          "order": "flexible",
          "properties": [
            "position",
            "inset",
            ...logicalProperties("inset"),
            "top",
            "right",
            "bottom",
            "left",
            "z-index",

          ],
        },
        {
          "emptyLineBefore": "never",
          "order": "flexible",
          "properties": [
            "box-sizing",
            "display",
            "table-layout",
            "float",
            "clear",
            "vertical-align",

            "grid",
            "grid-area",
            "grid-auto-columns",
            "grid-auto-flow",
            "grid-auto-rows",
            "grid-column",
            "grid-column-start",
            "grid-column-end",
            "grid-column-gap",
            "grid-gap",
            "grid-row",
            "grid-row-start",
            "grid-row-end",
            "grid-row-gap",
            "grid-template",
            "grid-template-areas",
            "grid-template-columns",
            "grid-template-rows",
            "gap",

            "flex",
            "flex-basis",
            "flex-direction",
            "flex-flow",
            "flex-grow",
            "flex-shrink",
            "flex-wrap",
            "justify-content",
            "align-items",
            "align-content",
            "align-self",
            "order",

            "width",
            "height",
            "max-width",
            "max-height",
            "min-height",
            "min-width",

            'inline-size',
            'max-inline-size',
            'min-inline-size',
            'block-size',
            'max-block-size',
            'min-block-size',

            "padding",
            ...tblrProperties("padding"),
            ...logicalProperties("padding"),
            "margin",
            ...tblrProperties("margin"),
            ...logicalProperties("margin"),

            "overflow",
            "overflow-x",
            "overflow-y",
            "overflow-scrolling",
          ],
        },
        {
          "emptyLineBefore": "never",
          "order": "flexible",
          "properties": [
            "border",
            ...logicalProperties("border"),
            ...logicalProperties("border", "color"),
            ...logicalProperties("border", "style"),
            ...logicalProperties("border", "width"),
            ...tblrProperties("border"),
            ...tblrProperties("border", "color", true),
            ...tblrProperties("border", "style"),
            ...tblrProperties("border", "width"),
            "border-start-start-radius",
            "border-start-end-radius",
            "border-end-start-radius",
            "border-end-end-radius",
            "border-bottom-left-radius",
            "border-bottom-right-radius",
            "border-top-left-radius",
            "border-top-right-radius",
            "border-collapse",
            "border-color",
            "border-image",
            "border-image-outset",
            "border-image-repeat",
            "border-image-slice",
            "border-image-source",
            "border-image-width",
            "border-radius",
            "border-spacing",
            "border-style",
            "border-width",
            "outline",
            "outline-color",
            "outline-offset",
            "outline-style",
            "outline-width",
            "background",
            "background-attachment",
            "background-blend-mode",
            "background-clip",
            "background-color",
            "background-image",
            "background-origin",
            "background-position",
            "background-repeat",
            "background-size",
            "box-shadow",
          ],
        },
        {
          "emptyLineBefore": "never",
          "order": "flexible",
          "properties": [
            "color",
            "font",
            "font-family",
            "font-size",
            "font-style",
            "font-weight",
            "line-height",
            "text-align",
            "text-decoration",
            "text-transform",
            "text-indent",
            "text-overflow",
            "white-space",
            "word-break",
            "word-wrap",
            "text-rendering",
            "font-smoothing",
            "letter-spacing",
          ],
        },
        {
          "emptyLineBefore": "never",
          "order": "flexible",
          "properties": [
            "transform",
            "transform-origin",
            "transform-box",
            "transform-style",
            "opacity",
            "visibility",
            "transition",
            "transition-delay",
            "transition-duration",
            "transition-property",
            "transition-timing-function",
            "animation",
            "animation-delay",
            "animation-direction",
            "animation-duration",
            "animation-fill-mode",
            "animation-iteration-count",
            "animation-name",
            "animation-play-state",
            "animation-timing-function",
            "will-change",
            "perspective",
          ],
        },
        {
          "emptyLineBefore": "never",
          "order": "flexible",
          "properties": [
            "cursor",
            "pointer-events",
            "filter",
            "appearance",
          ],
        },
      ],
      {
        "unspecified": "bottom",
      },
    ],
  },
};
